# Site Settings
title: Web of Origins
description: Visualising the connections between products, materials, industries, and their origins.
author: Web of Origins
url: https://weboforigins.com
baseurl: ""
logo: /src/Assets/logo.svg

# Build Settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Includes & Excludes
include:
  - _pages
  - blog
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Excerpt
excerpt_separator: <!--more-->

# Minima Theme (optional overrides)
theme: minima
minima:
  skin: auto
  social_links:
    twitter: WebOfOrigins
    linkedin: company/weboforigins
    facebook: WebOfOrigins
