# Site Settings
title: Web of Origins
description: Map the origins of products and materials. Explore the connections between ingredients, industries, supply chains, and their impacts.
author: Nhut Hoang-Don
url: https://weboforigins.com
baseurl: ""
logo: /src/Assets/logo.svg

# Build Settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Includes & Excludes
include:
  - _pages
  - blog
  - insights
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-archives
  - jekyll-tagging

# Defaults
defaults:
  -
    scope:
      path: "insights"
      type: "posts"
    values:
      layout: "post"
      permalink: /insights/:title

# Excerpt
excerpt_separator: <!--more-->

# Minima Theme (optional overrides)
theme: minima
minima:
  skin: auto
  social_links:
    twitter: WebOfOrigins
    linkedin: company/weboforigins
    facebook: WebOfOrigins


collections:
  posts:
    output: true
    permalink: /insights/:title


tagging:
  enabled: true
  layout: post
  permalink: /taglist/:name/
  dir: tags
  permalink_style: pretty