title: Web of Origins
theme: minima
plugins:
  - jekyll-feed
baseurl: ""
url: "https://www.weboforigins.com"
excerpt_separator: <!--more-->
markdown: kramdown
sass:
  style: compressed
  sass_dir: _sass

include: ["_pages", "blog"]
